### ISSUE TITLE
displayName is not available

### ISSUE THREAD

**Issue by erik-t** [codediodeio/cloud-functions-master-course#1]
Just wanted to point out that user.displayName on the line below would not be available because it is added via an additional call "updateProfile" after signing up and the onCreate trigger is called before the displayName has been added to the auth user obj.

https://github.com/codediodeio/cloud-functions-master-course/blob/master/functions/src/auth.ts#L14

**Comment by codediodeio** [comment]
Actually displayName should be on the user object when a user logs in with OAuth. We might want add an extra default to the code like this to prevent sending an `undefined` value and breaking Firestore. 

```
  return userRef.set({
      name: user.displayName || null,
    });
```

**Comment by erik-t** [comment]
Ah yes. Your course actually doesn't cover sign in with email and password which is where I was seeing the issue.
